### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by reversebro** [mehmetbeyHZ/tiktokapi#1]
Hello
stdClass Object ( [data] => stdClass Object ( [captcha] => [description] => Missing ID certification information [error_code] => 2 ) [message] => error )

**Comment by mt-ks** [comment]
i will update

**Comment by reversebro** [comment]
Hello
Whats of last status

**Comment by reversebro** [comment]
??

**Comment by reversebro** [comment]
Dear pls solve this issue

**Comment by reversebro** [comment]
Why closed?
