### ISSUE TITLE
Response: NULL

### ISSUE THREAD

**Issue by manguon** [mehmetbeyHZ/tiktokapi#3]
Hello, 

My code: 

`require_once( 'TiktokApi.php');
$tiktok = new TiktokApi();
$user_id = '6544940070637961218';
$info = $tiktok->userInfo($user_id); 
var_dump ($info);`

But, display: NULL ???

Please help me.

Thanks

**Comment by manguon** [comment]
> require_once( 'TiktokApi.php'); 
> $tiktok = new TiktokApi(); 
> $user_id = '6544940070637961218'; 
> $info = $tiktok->userInfo($user_id); 
> var_dump ($info);

**Comment by umeshdepale** [comment]
change the device info
