### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by hrehman200** [mehmetbeyHZ/tiktokapi#4]
I entered my username and password, but tiktop returns empty json fields. Only message is set to error.

`object(stdClass)[3]
  public 'data' => 
    object(stdClass)[2]
      public 'captcha' => string '' (length=0)
      public 'description' => string '' (length=0)
      public 'error_code' => int 1105
  public 'message' => string 'error' (length=5)`

**Comment by mt-ks** [comment]
error_code 1105 is puzzle captcha. you should pass the captcha manually. API Does not supports maybe i will update repo for automatically pass.

`
https://verification-va.musical.ly/view?aid=1233&lang=tr&app_name=musical_ly&iid=YOUR_IID&vc=VERSION_CODE&did=YOUR_DEVICEID&ch=googleplay&os=0&challenge_code=1105
`
